# Generated by Django 4.1.3 on 2022-11-30 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaHorario', models.DateTimeField(auto_now_add=True)),
                ('fechaHorarioFin', models.DateTimeField(auto_now_add=True)),
                ('link', models.TextField(max_length=1000)),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=8)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Forma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=8)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaPago', models.DateTimeField(auto_now_add=True)),
                ('valor', models.IntegerField()),
                ('comision', models.IntegerField()),
                ('estado', models.CharField(max_length=20)),
                ('idAgenda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.agenda')),
                ('idFormaPago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.forma')),
                ('rutAlumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=20)),
                ('fechaAsistencia', models.DateTimeField(auto_now_add=True)),
                ('rutAlumno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.alumno')),
            ],
        ),
        migrations.AddField(
            model_name='agenda',
            name='idAsignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.asignatura'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='idPlataforma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.plataforma'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='rutProfesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.profesor'),
        ),
    ]
